---
# tasks file for sssd

- name: install sssd packages ({{ sssd_packages | join(', ') }})
  package:
    name: "{{ sssd_packages }}"
  tags:
  - packages


- name: configure sssd.conf
  block:
  - name: create config snippet directory
    file:
      dest: /etc/sssd/conf.d
      state: directory
      mode: '0644'

  - name: check for conf.d/00-sssd.conf
    file: &00_sssd_file
      dest: /etc/sssd/conf.d/00-sssd.conf
      mode: '0600'
      owner: "{{ sssd_user }}"
      group: "{{ sssd_user }}"
    args:
      state: file

  rescue:
  - name: workaround for https://github.com/ansible/ansible/issues/61253
    meta: noop

  - name: check for sssd.conf
    block:
    - name: copy conf.d/00-sssd.conf from sssd.conf
      copy:
        dest: /etc/sssd/conf.d/00-sssd.conf
        src: /etc/sssd/sssd.conf
        remote_src: yes
        mode: '0600'
        owner: "{{ sssd_user }}"
        group: "{{ sssd_user }}"

    rescue:
    - name: create empty sssd.conf
      file:
        <<: *00_sssd_file
        state: touch

- name: find sssd version
  block:
  - name: find sssd version
    command: sssd --version
    check_mode: no
    changed_when: no
    register: sssd_version_check
  rescue:
  - name: older sssd returns 1 for 'sssd --version'
    assert:
      that: sssd_version_check.rc == 1

  # TODO: rpm -q sssd --queryformat '%{RPMTAG_VERSION}'
  - name: assume 1.5.1 (RHEL 5) on version check failure
    set_fact:
      sssd_version_check: "{{ sssd_version_check | combine(dict(stdout='1.5.1')) }}"

- name: symlink main sssd.conf on snippet-supporting versions
  file:
    dest: /etc/sssd/sssd.conf
    src: /etc/sssd/conf.d/00-sssd.conf
    state: link
    owner: "{{ sssd_user }}"
    group: "{{ sssd_user }}"
  when: sssd_version is version_compare(sssd_version_config_snippet_supported, '>=')

- name: set config_file_version on older sssd
  ini_file:
    dest: /etc/sssd/conf.d/00-sssd.conf
    section: sssd
    option: config_file_version
    value: 2
  when: sssd_version is version_compare(sssd_version_config_file_version_not_req, '<')
